services:
  db:
    image: postgres
    volumes:
      - db_volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: sh /scripts/command.sh
    volumes:
      - .:/app
      - bundle_volumes:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle_volumes:
  db_volumes: